// Menu item: Configure new AP
#ifdef AUTOCONNECT_MENULABEL_CONFIGNEW
#undef AUTOCONNECT_MENULABEL_CONFIGNEW
#define AUTOCONNECT_MENULABEL_CONFIGNEW "Nastavení nové WIFI"
#endif // !AUTOCONNECT_MENULABEL_CONFIGNEW

// Menu item: Open SSIDs
#ifdef AUTOCONNECT_MENULABEL_OPENSSIDS
#undef AUTOCONNECT_MENULABEL_OPENSSIDS
#define AUTOCONNECT_MENULABEL_OPENSSIDS "Uložené WiFi"
#endif // !AUTOCONNECT_MENULABEL_OPENSSIDS

// Menu item: Disconnect
#ifdef AUTOCONNECT_MENULABEL_DISCONNECT
#undef AUTOCONNECT_MENULABEL_DISCONNECT
#define AUTOCONNECT_MENULABEL_DISCONNECT "Odpojit"
#endif // !AUTOCONNECT_MENULABEL_DISCONNECT

// Menu item: Reset...
#ifdef AUTOCONNECT_MENULABEL_RESET
#undef AUTOCONNECT_MENULABEL_RESET
#define AUTOCONNECT_MENULABEL_RESET "Restart zařízení"
#endif // !AUTOCONNECT_MENULABEL_RESET

// Menu item: HOME
#ifdef AUTOCONNECT_MENULABEL_HOME
#undef AUTOCONNECT_MENULABEL_HOME
#define AUTOCONNECT_MENULABEL_HOME "Úvod"
#endif // !AUTOCONNECT_MENULABEL_HOME

// Menu item: ACROOT
#ifdef AUTOCONNECT_MENULABEL_ACROOT
#undef AUTOCONNECT_MENULABEL_ACROOT
#define AUTOCONNECT_MENULABEL_ACROOT "Informace o zařízení"
#endif // !AUTOCONNECT_MENULABEL_ACROOT

// Menu item: Update
#ifdef AUTOCONNECT_MENULABEL_UPDATE
#undef AUTOCONNECT_MENULABEL_UPDATE
#define AUTOCONNECT_MENULABEL_UPDATE "Přehrát firmware"
#endif // !AUTOCONNECT_MENULABEL_UPDATE

// Button label: RESET
#ifdef AUTOCONNECT_BUTTONLABEL_RESET
#undef AUTOCONNECT_BUTTONLABEL_RESET
#define AUTOCONNECT_BUTTONLABEL_RESET "Reset"
#endif // !AUTOCONNECT_BUTTONLABEL_RESET

// Page title: Page not found
#ifdef AUTOCONNECT_PAGETITLE_NOTFOUND
#undef AUTOCONNECT_PAGETITLE_NOTFOUND
#define AUTOCONNECT_PAGETITLE_NOTFOUND "Stránka nenalezena"
#endif // !AUTOCONNECT_PAGETITLE_NOTFOUND

// Page title: AutoConnect resetting
#ifdef AUTOCONNECT_PAGETITLE_RESETTING
#undef AUTOCONNECT_PAGETITLE_RESETTING
#define AUTOCONNECT_PAGETITLE_RESETTING "Restartuji"
#endif // !AUTOCONNECT_PAGETITLE_RESETTING

// Page title: AutoConnect statistics
#ifdef AUTOCONNECT_PAGETITLE_STATISTICS
#undef AUTOCONNECT_PAGETITLE_STATISTICS
#define AUTOCONNECT_PAGETITLE_STATISTICS "Statistika"
#endif // !AUTOCONNECT_PAGETITLE_STATISTICS

// Page statistics row: Established connection
#ifdef AUTOCONNECT_PAGESTATS_ESTABLISHEDCONNECTION
#undef AUTOCONNECT_PAGESTATS_ESTABLISHEDCONNECTION
#define AUTOCONNECT_PAGESTATS_ESTABLISHEDCONNECTION "Navázané spojení"
#endif // !AUTOCONNECT_PAGESTATS_ESTABLISHEDCONNECTION

// Page statistics row: Mode
#ifdef AUTOCONNECT_PAGESTATS_MODE
#undef AUTOCONNECT_PAGESTATS_MODE
#define AUTOCONNECT_PAGESTATS_MODE "Mód"
#endif // !AUTOCONNECT_PAGESTATS_MODE

// Page statistics row: IP
#ifdef AUTOCONNECT_PAGESTATS_IP
#undef AUTOCONNECT_PAGESTATS_IP
#define AUTOCONNECT_PAGESTATS_IP "IP adresa"
#endif // !AUTOCONNECT_PAGESTATS_IP

// Page statistics row: GW
#ifdef AUTOCONNECT_PAGESTATS_GATEWAY
#undef AUTOCONNECT_PAGESTATS_GATEWAY
#define AUTOCONNECT_PAGESTATS_GATEWAY "Brána"
#endif // !AUTOCONNECT_PAGESTATS_GATEWAY

// Page statistics row: Subnet mask
#ifdef AUTOCONNECT_PAGESTATS_SUBNETMASK
#undef AUTOCONNECT_PAGESTATS_SUBNETMASK
#define AUTOCONNECT_PAGESTATS_SUBNETMASK "Maska podsítě"
#endif // !AUTOCONNECT_PAGESTATS_SUBNETMASK

// Page statistics row: SoftAP IP
#ifdef AUTOCONNECT_PAGESTATS_SOFTAPIP
#undef AUTOCONNECT_PAGESTATS_SOFTAPIP
#define AUTOCONNECT_PAGESTATS_SOFTAPIP "AP IP adresa"
#endif // !AUTOCONNECT_PAGESTATS_SOFTAPIP

// Page statistics row: AP MAC
#ifdef AUTOCONNECT_PAGESTATS_APMAC
#undef AUTOCONNECT_PAGESTATS_APMAC
#define AUTOCONNECT_PAGESTATS_APMAC "AP MAC"
#endif // !AUTOCONNECT_PAGESTATS_APMAC

// Page statistics row: STA MAC
#ifdef AUTOCONNECT_PAGESTATS_STAMAC
#undef AUTOCONNECT_PAGESTATS_STAMAC
#define AUTOCONNECT_PAGESTATS_STAMAC "STA MAC"
#endif // !AUTOCONNECT_PAGESTATS_STAMAC

// Page statistics row: Channel
#ifdef AUTOCONNECT_PAGESTATS_CHANNEL
#undef AUTOCONNECT_PAGESTATS_CHANNEL
#define AUTOCONNECT_PAGESTATS_CHANNEL "Kanál"
#endif // !AUTOCONNECT_PAGESTATS_CHANNEL

// Page statistics row: dBm
#ifdef AUTOCONNECT_PAGESTATS_DBM
#undef AUTOCONNECT_PAGESTATS_DBM
#define AUTOCONNECT_PAGESTATS_DBM "dBm"
#endif // !AUTOCONNECT_PAGESTATS_DBM

// Page statistics row: Chip ID
#ifdef AUTOCONNECT_PAGESTATS_CHIPID
#undef AUTOCONNECT_PAGESTATS_CHIPID
#define AUTOCONNECT_PAGESTATS_CHIPID "ID čipu"
#endif // !AUTOCONNECT_PAGESTATS_CHIPID

// Page statistics row: CPU Freq.
#ifdef AUTOCONNECT_PAGESTATS_CPUFREQ
#undef AUTOCONNECT_PAGESTATS_CPUFREQ
#define AUTOCONNECT_PAGESTATS_CPUFREQ "Frekvence CPU"
#endif // !AUTOCONNECT_PAGESTATS_CPUFREQ

// Page statistics row: Flash size
#ifdef AUTOCONNECT_PAGESTATS_FLASHSIZE
#undef AUTOCONNECT_PAGESTATS_FLASHSIZE
#define AUTOCONNECT_PAGESTATS_FLASHSIZE "Velikost paměti"
#endif // !AUTOCONNECT_PAGESTATS_FLASHSIZE

// Page statistics row: Free memory
#ifdef AUTOCONNECT_PAGESTATS_FREEMEM
#undef AUTOCONNECT_PAGESTATS_FREEMEM
#define AUTOCONNECT_PAGESTATS_FREEMEM "Volné paměti"
#endif // !AUTOCONNECT_PAGESTATS_FREEMEM

// Page title: AutoConnect config
#ifdef AUTOCONNECT_PAGETITLE_CONFIG
#undef AUTOCONNECT_PAGETITLE_CONFIG
#define AUTOCONNECT_PAGETITLE_CONFIG "Konfigurace"
#endif // !AUTOCONNECT_PAGETITLE_CONFIG

// Page config text: Total:
#ifdef AUTOCONNECT_PAGECONFIG_TOTAL
#undef AUTOCONNECT_PAGECONFIG_TOTAL
#define AUTOCONNECT_PAGECONFIG_TOTAL "Celkem: "
#endif // !AUTOCONNECT_PAGECONFIG_TOTAL

// Page config text: Hidden:
#ifdef AUTOCONNECT_PAGECONFIG_HIDDEN
#undef AUTOCONNECT_PAGECONFIG_HIDDEN
#define AUTOCONNECT_PAGECONFIG_HIDDEN "Skryté: "
#endif // !AUTOCONNECT_PAGECONFIG_HIDDEN

// Page config text: SSID
#ifdef AUTOCONNECT_PAGECONFIG_SSID
#undef AUTOCONNECT_PAGECONFIG_SSID
#define AUTOCONNECT_PAGECONFIG_SSID "SSID"
#endif // !AUTOCONNECT_PAGECONFIG_SSID

// Page config text: Passphrase
#ifdef AUTOCONNECT_PAGECONFIG_PASSPHRASE
#undef AUTOCONNECT_PAGECONFIG_PASSPHRASE
#define AUTOCONNECT_PAGECONFIG_PASSPHRASE "Heslo"
#endif // !AUTOCONNECT_PAGECONFIG_PASSPHRASE

// Page config text: Enable DHCP
#ifdef AUTOCONNECT_PAGECONFIG_ENABLEDHCP
#undef AUTOCONNECT_PAGECONFIG_ENABLEDHCP
#define AUTOCONNECT_PAGECONFIG_ENABLEDHCP "Zapnout DHCP"
#endif // !AUTOCONNECT_PAGECONFIG_ENABLEDHCP

// Page config text: Apply
#ifdef AUTOCONNECT_PAGECONFIG_APPLY
#undef AUTOCONNECT_PAGECONFIG_APPLY
#define AUTOCONNECT_PAGECONFIG_APPLY "Uložit"
#endif // !AUTOCONNECT_PAGECONFIG_APPLY

// Page title: AutoConnect credentials
#ifdef AUTOCONNECT_PAGETITLE_CREDENTIALS
#undef AUTOCONNECT_PAGETITLE_CREDENTIALS
#define AUTOCONNECT_PAGETITLE_CREDENTIALS "Pověření"
#endif // !AUTOCONNECT_PAGETITLE_CREDENTIALS

// Page title: AutoConnect connecting
#ifdef AUTOCONNECT_PAGETITLE_CONNECTING
#undef AUTOCONNECT_PAGETITLE_CONNECTING
#define AUTOCONNECT_PAGETITLE_CONNECTING "Připojuji"
#endif // !AUTOCONNECT_PAGETITLE_CONNECTING

// Page title: AutoConnect connection failed
#ifdef AUTOCONNECT_PAGETITLE_CONNECTIONFAILED
#undef AUTOCONNECT_PAGETITLE_CONNECTIONFAILED
#define AUTOCONNECT_PAGETITLE_CONNECTIONFAILED "Připojení selhalo"
#endif // !AUTOCONNECT_PAGETITLE_CONNECTIONFAILED

// Page connection failed: Connection Failed
#ifdef AUTOCONNECT_PAGECONNECTIONFAILED_CONNECTIONFAILED
#undef AUTOCONNECT_PAGECONNECTIONFAILED_CONNECTIONFAILED
#define AUTOCONNECT_PAGECONNECTIONFAILED_CONNECTIONFAILED "Připojení selhalo"
#endif // !AUTOCONNECT_PAGECONNECTIONFAILED_CONNECTIONFAILED

// Page title: AutoConnect disconnected
#ifdef AUTOCONNECT_PAGETITLE_DISCONNECTED
#undef AUTOCONNECT_PAGETITLE_DISCONNECTED
#define AUTOCONNECT_PAGETITLE_DISCONNECTED "Odpojeno"
#endif // !AUTOCONNECT_PAGETITLE_DISCONNECTED

// Text: No saved credentials.
#ifdef AUTOCONNECT_TEXT_NOSAVEDCREDENTIALS
#undef AUTOCONNECT_TEXT_NOSAVEDCREDENTIALS
#define AUTOCONNECT_TEXT_NOSAVEDCREDENTIALS "Žádné uložené WiFi sítě."
#endif // !AUTOCONNECT_TEXT_NOSAVEDCREDENTIALS

// Menu Text: Connecting
#ifdef AUTOCONNECT_MENUTEXT_CONNECTING
#undef AUTOCONNECT_MENUTEXT_CONNECTING
#define AUTOCONNECT_MENUTEXT_CONNECTING "Připojuji"
#endif // !AUTOCONNECT_MENUTEXT_CONNECTING

// Menu Text: Disconnect
#ifdef AUTOCONNECT_MENUTEXT_DISCONNECT
#undef AUTOCONNECT_MENUTEXT_DISCONNECT
#define AUTOCONNECT_MENUTEXT_DISCONNECT "Odpojit"
#endif // !AUTOCONNECT_MENUTEXT_DISCONNECT

// Menu Text: Failed
#ifdef AUTOCONNECT_MENUTEXT_FAILED
#undef AUTOCONNECT_MENUTEXT_FAILED
#define AUTOCONNECT_MENUTEXT_FAILED "Připojení selhalo"
#endif // !AUTOCONNECT_MENUTEXT_FAILED

// Menu colors
// The following three color code items determine the color scheme of
// the menu. In addition to hexadecimal color values, you can specify
// 140 standard color names that apply to CSS.
// To be no sense of discomfort, select the same series of values for
// the background and the active item.

// Menu text foreground color
#ifdef AUTOCONNECT_MENUCOLOR_TEXT
#undef AUTOCONNECT_MENUCOLOR_TEXT
#define AUTOCONNECT_MENUCOLOR_TEXT "#fff"
//#define AUTOCONNECT_MENUCOLOR_TEXT        "#fffacd"
#endif // !AUTOCONNECT_MENUCOLOR_TEXT

// Menu background color
#ifdef AUTOCONNECT_MENUCOLOR_BACKGROUND
#undef AUTOCONNECT_MENUCOLOR_BACKGROUND
#define AUTOCONNECT_MENUCOLOR_BACKGROUND "#263238"
// #define AUTOCONNECT_MENUCOLOR_BACKGROUND  "#696969"
#endif // !AUTOCONNECT_MENUCOLOR_BACKGROUND

// Background color with active menu items and mouse hover
#ifdef AUTOCONNECT_MENUCOLOR_ACTIVE
#undef AUTOCONNECT_MENUCOLOR_ACTIVE
#define AUTOCONNECT_MENUCOLOR_ACTIVE "#37474f"
// #define AUTOCONNECT_MENUCOLOR_ACTIVE      "#808080"
#endif
